spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/db_account
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver

    druid:
#      Spring组件监控
      aop-patterns: com.atguigu.*
      filters: stat,wall
      stat-view-servlet:
        enabled: true
        login-username: admin
        login-password: 123456
        reset-enable: false
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.png,*css,/druid/*'
      filter:
        stat:
          slow-sql-millis: 1000
          log-slow-sql: true
          enabled: true
        wall:
          enabled: true

  redis:
    host: 47.105.147.6
    port: 6379
    client-type: jedis
    jedis:
      pool:
        max-active: 10
        min-idle: 5
#    lettuce:
#      pool:
#        max-active:  10
#        min-idle: 5